apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-computing-milestone-3-fe-web
  labels:
    app: cloud-computing-milestone-3-fe-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloud-computing-milestone-3-fe-web
  template:
    metadata:
      labels:
        app: cloud-computing-milestone-3-fe-web
    spec:
      containers:
        - name: cloud-computing-milestone-3-fe-web
          image: gcr.io/strapi-385510/cloud_computing_milestone_3_fe-web:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: "production"
      restartPolicy: Always